//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace Pithline.FMS.TechnicalInspection.UILogic.TIService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    public partial class CallContext : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CompanyField;
        
        private string LanguageField;
        
        private string LogonAsUserField;
        
        private string MessageIdField;
        
        private System.Collections.Generic.Dictionary<string, string> PropertyBagField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogonAsUser {
            get {
                return this.LogonAsUserField;
            }
            set {
                if ((object.ReferenceEquals(this.LogonAsUserField, value) != true)) {
                    this.LogonAsUserField = value;
                    this.RaisePropertyChanged("LogonAsUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> PropertyBag {
            get {
                return this.PropertyBagField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyBagField, value) != true)) {
                    this.PropertyBagField = value;
                    this.RaisePropertyChanged("PropertyBag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class AifFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CustomDetailXmlField;
        
        private System.Collections.ObjectModel.ObservableCollection<Pithline.FMS.TechnicalInspection.UILogic.TIService.FaultMessageList> FaultMessageListArrayField;
        
        private System.Collections.ObjectModel.ObservableCollection<Pithline.FMS.TechnicalInspection.UILogic.TIService.InfologMessage> InfologMessageListField;
        
        private string StackTraceField;
        
        private int XppExceptionTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomDetailXml {
            get {
                return this.CustomDetailXmlField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomDetailXmlField, value) != true)) {
                    this.CustomDetailXmlField = value;
                    this.RaisePropertyChanged("CustomDetailXml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Pithline.FMS.TechnicalInspection.UILogic.TIService.FaultMessageList> FaultMessageListArray {
            get {
                return this.FaultMessageListArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageListArrayField, value) != true)) {
                    this.FaultMessageListArrayField = value;
                    this.RaisePropertyChanged("FaultMessageListArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Pithline.FMS.TechnicalInspection.UILogic.TIService.InfologMessage> InfologMessageList {
            get {
                return this.InfologMessageListField;
            }
            set {
                if ((object.ReferenceEquals(this.InfologMessageListField, value) != true)) {
                    this.InfologMessageListField = value;
                    this.RaisePropertyChanged("InfologMessageList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XppExceptionType {
            get {
                return this.XppExceptionTypeField;
            }
            set {
                if ((this.XppExceptionTypeField.Equals(value) != true)) {
                    this.XppExceptionTypeField = value;
                    this.RaisePropertyChanged("XppExceptionType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessageList", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessageList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DocumentField;
        
        private string DocumentOperationField;
        
        private System.Collections.ObjectModel.ObservableCollection<Pithline.FMS.TechnicalInspection.UILogic.TIService.FaultMessage> FaultMessageArrayField;
        
        private string FieldField;
        
        private string ServiceField;
        
        private string ServiceOperationField;
        
        private string ServiceOperationParameterField;
        
        private string XPathField;
        
        private string XmlLineField;
        
        private string XmlPositionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Document {
            get {
                return this.DocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentField, value) != true)) {
                    this.DocumentField = value;
                    this.RaisePropertyChanged("Document");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentOperation {
            get {
                return this.DocumentOperationField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentOperationField, value) != true)) {
                    this.DocumentOperationField = value;
                    this.RaisePropertyChanged("DocumentOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Pithline.FMS.TechnicalInspection.UILogic.TIService.FaultMessage> FaultMessageArray {
            get {
                return this.FaultMessageArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageArrayField, value) != true)) {
                    this.FaultMessageArrayField = value;
                    this.RaisePropertyChanged("FaultMessageArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field {
            get {
                return this.FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldField, value) != true)) {
                    this.FieldField = value;
                    this.RaisePropertyChanged("Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Service {
            get {
                return this.ServiceField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceField, value) != true)) {
                    this.ServiceField = value;
                    this.RaisePropertyChanged("Service");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperation {
            get {
                return this.ServiceOperationField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOperationField, value) != true)) {
                    this.ServiceOperationField = value;
                    this.RaisePropertyChanged("ServiceOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperationParameter {
            get {
                return this.ServiceOperationParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOperationParameterField, value) != true)) {
                    this.ServiceOperationParameterField = value;
                    this.RaisePropertyChanged("ServiceOperationParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XPath {
            get {
                return this.XPathField;
            }
            set {
                if ((object.ReferenceEquals(this.XPathField, value) != true)) {
                    this.XPathField = value;
                    this.RaisePropertyChanged("XPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlLine {
            get {
                return this.XmlLineField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlLineField, value) != true)) {
                    this.XmlLineField = value;
                    this.RaisePropertyChanged("XmlLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlPosition {
            get {
                return this.XmlPositionField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlPositionField, value) != true)) {
                    this.XmlPositionField = value;
                    this.RaisePropertyChanged("XmlPosition");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessage", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public partial class InfologMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Pithline.FMS.TechnicalInspection.UILogic.TIService.InfologMessageType InfologMessageTypeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pithline.FMS.TechnicalInspection.UILogic.TIService.InfologMessageType InfologMessageType {
            get {
                return this.InfologMessageTypeField;
            }
            set {
                if ((this.InfologMessageTypeField.Equals(value) != true)) {
                    this.InfologMessageTypeField = value;
                    this.RaisePropertyChanged("InfologMessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CodeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessageType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MzkTechnicalTasksContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class MzkTechnicalTasksContract : Pithline.FMS.TechnicalInspection.UILogic.TIService.XppObjectBase {
        
        private string parmCaseCategoryField;
        
        private string parmCaseIdField;
        
        private long parmCaseRecIDField;
        
        private long parmCaseServiceRecIDField;
        
        private string parmContactPersonAddressField;
        
        private string parmContactPersonNameField;
        
        private string parmContactPersonPhoneField;
        
        private string parmCustAccountField;
        
        private string parmCustAddressField;
        
        private string parmCustNameField;
        
        private string parmCustPhoneField;
        
        private Pithline.FMS.TechnicalInspection.UILogic.TIService.EEPActionStep parmEEPActionStepField;
        
        private string parmEmailField;
        
        private System.DateTime parmInspectionDueDateField;
        
        private string parmServiceIdField;
        
        private long parmServiceRecIDField;
        
        private string parmStatusField;
        
        private System.DateTime parmStatusDueDateField;
        
        private string parmUserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmCaseCategory {
            get {
                return this.parmCaseCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.parmCaseCategoryField, value) != true)) {
                    this.parmCaseCategoryField = value;
                    this.RaisePropertyChanged("parmCaseCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmCaseId {
            get {
                return this.parmCaseIdField;
            }
            set {
                if ((object.ReferenceEquals(this.parmCaseIdField, value) != true)) {
                    this.parmCaseIdField = value;
                    this.RaisePropertyChanged("parmCaseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long parmCaseRecID {
            get {
                return this.parmCaseRecIDField;
            }
            set {
                if ((this.parmCaseRecIDField.Equals(value) != true)) {
                    this.parmCaseRecIDField = value;
                    this.RaisePropertyChanged("parmCaseRecID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long parmCaseServiceRecID {
            get {
                return this.parmCaseServiceRecIDField;
            }
            set {
                if ((this.parmCaseServiceRecIDField.Equals(value) != true)) {
                    this.parmCaseServiceRecIDField = value;
                    this.RaisePropertyChanged("parmCaseServiceRecID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmContactPersonAddress {
            get {
                return this.parmContactPersonAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.parmContactPersonAddressField, value) != true)) {
                    this.parmContactPersonAddressField = value;
                    this.RaisePropertyChanged("parmContactPersonAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmContactPersonName {
            get {
                return this.parmContactPersonNameField;
            }
            set {
                if ((object.ReferenceEquals(this.parmContactPersonNameField, value) != true)) {
                    this.parmContactPersonNameField = value;
                    this.RaisePropertyChanged("parmContactPersonName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmContactPersonPhone {
            get {
                return this.parmContactPersonPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.parmContactPersonPhoneField, value) != true)) {
                    this.parmContactPersonPhoneField = value;
                    this.RaisePropertyChanged("parmContactPersonPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmCustAccount {
            get {
                return this.parmCustAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.parmCustAccountField, value) != true)) {
                    this.parmCustAccountField = value;
                    this.RaisePropertyChanged("parmCustAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmCustAddress {
            get {
                return this.parmCustAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.parmCustAddressField, value) != true)) {
                    this.parmCustAddressField = value;
                    this.RaisePropertyChanged("parmCustAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmCustName {
            get {
                return this.parmCustNameField;
            }
            set {
                if ((object.ReferenceEquals(this.parmCustNameField, value) != true)) {
                    this.parmCustNameField = value;
                    this.RaisePropertyChanged("parmCustName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmCustPhone {
            get {
                return this.parmCustPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.parmCustPhoneField, value) != true)) {
                    this.parmCustPhoneField = value;
                    this.RaisePropertyChanged("parmCustPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pithline.FMS.TechnicalInspection.UILogic.TIService.EEPActionStep parmEEPActionStep {
            get {
                return this.parmEEPActionStepField;
            }
            set {
                if ((this.parmEEPActionStepField.Equals(value) != true)) {
                    this.parmEEPActionStepField = value;
                    this.RaisePropertyChanged("parmEEPActionStep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmEmail {
            get {
                return this.parmEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.parmEmailField, value) != true)) {
                    this.parmEmailField = value;
                    this.RaisePropertyChanged("parmEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime parmInspectionDueDate {
            get {
                return this.parmInspectionDueDateField;
            }
            set {
                if ((this.parmInspectionDueDateField.Equals(value) != true)) {
                    this.parmInspectionDueDateField = value;
                    this.RaisePropertyChanged("parmInspectionDueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmServiceId {
            get {
                return this.parmServiceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.parmServiceIdField, value) != true)) {
                    this.parmServiceIdField = value;
                    this.RaisePropertyChanged("parmServiceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long parmServiceRecID {
            get {
                return this.parmServiceRecIDField;
            }
            set {
                if ((this.parmServiceRecIDField.Equals(value) != true)) {
                    this.parmServiceRecIDField = value;
                    this.RaisePropertyChanged("parmServiceRecID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmStatus {
            get {
                return this.parmStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.parmStatusField, value) != true)) {
                    this.parmStatusField = value;
                    this.RaisePropertyChanged("parmStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime parmStatusDueDate {
            get {
                return this.parmStatusDueDateField;
            }
            set {
                if ((this.parmStatusDueDateField.Equals(value) != true)) {
                    this.parmStatusDueDateField = value;
                    this.RaisePropertyChanged("parmStatusDueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmUserID {
            get {
                return this.parmUserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.parmUserIDField, value) != true)) {
                    this.parmUserIDField = value;
                    this.RaisePropertyChanged("parmUserID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pithline.FMS.TechnicalInspection.UILogic.TIService.Mzk_ImageContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkCaseCategoryAuthorizationContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkCaseServiceAuthorizationContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkValidateUserContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalTasksContract))]
    public partial class XppObjectBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mzk_ImageContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class Mzk_ImageContract : Pithline.FMS.TechnicalInspection.UILogic.TIService.XppObjectBase {
        
        private string parmCaseNumberField;
        
        private string parmFileNameField;
        
        private string parmImageField;
        
        private string parmImageDataField;
        
        private string parmImageNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmCaseNumber {
            get {
                return this.parmCaseNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.parmCaseNumberField, value) != true)) {
                    this.parmCaseNumberField = value;
                    this.RaisePropertyChanged("parmCaseNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmFileName {
            get {
                return this.parmFileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.parmFileNameField, value) != true)) {
                    this.parmFileNameField = value;
                    this.RaisePropertyChanged("parmFileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmImage {
            get {
                return this.parmImageField;
            }
            set {
                if ((object.ReferenceEquals(this.parmImageField, value) != true)) {
                    this.parmImageField = value;
                    this.RaisePropertyChanged("parmImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmImageData {
            get {
                return this.parmImageDataField;
            }
            set {
                if ((object.ReferenceEquals(this.parmImageDataField, value) != true)) {
                    this.parmImageDataField = value;
                    this.RaisePropertyChanged("parmImageData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmImageName {
            get {
                return this.parmImageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.parmImageNameField, value) != true)) {
                    this.parmImageNameField = value;
                    this.RaisePropertyChanged("parmImageName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MzkCaseCategoryAuthorizationContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class MzkCaseCategoryAuthorizationContract : Pithline.FMS.TechnicalInspection.UILogic.TIService.XppObjectBase {
        
        private string parmActionField;
        
        private long parmCaseServiceRecIDField;
        
        private string parmCauseField;
        
        private string parmMajorComponentField;
        
        private long parmRecIDField;
        
        private string parmSubComponentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmAction {
            get {
                return this.parmActionField;
            }
            set {
                if ((object.ReferenceEquals(this.parmActionField, value) != true)) {
                    this.parmActionField = value;
                    this.RaisePropertyChanged("parmAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long parmCaseServiceRecID {
            get {
                return this.parmCaseServiceRecIDField;
            }
            set {
                if ((this.parmCaseServiceRecIDField.Equals(value) != true)) {
                    this.parmCaseServiceRecIDField = value;
                    this.RaisePropertyChanged("parmCaseServiceRecID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmCause {
            get {
                return this.parmCauseField;
            }
            set {
                if ((object.ReferenceEquals(this.parmCauseField, value) != true)) {
                    this.parmCauseField = value;
                    this.RaisePropertyChanged("parmCause");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmMajorComponent {
            get {
                return this.parmMajorComponentField;
            }
            set {
                if ((object.ReferenceEquals(this.parmMajorComponentField, value) != true)) {
                    this.parmMajorComponentField = value;
                    this.RaisePropertyChanged("parmMajorComponent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long parmRecID {
            get {
                return this.parmRecIDField;
            }
            set {
                if ((this.parmRecIDField.Equals(value) != true)) {
                    this.parmRecIDField = value;
                    this.RaisePropertyChanged("parmRecID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmSubComponent {
            get {
                return this.parmSubComponentField;
            }
            set {
                if ((object.ReferenceEquals(this.parmSubComponentField, value) != true)) {
                    this.parmSubComponentField = value;
                    this.RaisePropertyChanged("parmSubComponent");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MzkCaseServiceAuthorizationContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class MzkCaseServiceAuthorizationContract : Pithline.FMS.TechnicalInspection.UILogic.TIService.XppObjectBase {
        
        private System.Collections.ObjectModel.ObservableCollection<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkCaseCategoryAuthorizationContract> parmCaseCategoryAuthListField;
        
        private long parmCaseServiceRecIDField;
        
        private System.DateTime parmCompletionDateField;
        
        private string parmDamageCauseField;
        
        private long parmRecIDField;
        
        private string parmRecommendationField;
        
        private string parmRemedyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkCaseCategoryAuthorizationContract> parmCaseCategoryAuthList {
            get {
                return this.parmCaseCategoryAuthListField;
            }
            set {
                if ((object.ReferenceEquals(this.parmCaseCategoryAuthListField, value) != true)) {
                    this.parmCaseCategoryAuthListField = value;
                    this.RaisePropertyChanged("parmCaseCategoryAuthList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long parmCaseServiceRecID {
            get {
                return this.parmCaseServiceRecIDField;
            }
            set {
                if ((this.parmCaseServiceRecIDField.Equals(value) != true)) {
                    this.parmCaseServiceRecIDField = value;
                    this.RaisePropertyChanged("parmCaseServiceRecID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime parmCompletionDate {
            get {
                return this.parmCompletionDateField;
            }
            set {
                if ((this.parmCompletionDateField.Equals(value) != true)) {
                    this.parmCompletionDateField = value;
                    this.RaisePropertyChanged("parmCompletionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmDamageCause {
            get {
                return this.parmDamageCauseField;
            }
            set {
                if ((object.ReferenceEquals(this.parmDamageCauseField, value) != true)) {
                    this.parmDamageCauseField = value;
                    this.RaisePropertyChanged("parmDamageCause");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long parmRecID {
            get {
                return this.parmRecIDField;
            }
            set {
                if ((this.parmRecIDField.Equals(value) != true)) {
                    this.parmRecIDField = value;
                    this.RaisePropertyChanged("parmRecID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmRecommendation {
            get {
                return this.parmRecommendationField;
            }
            set {
                if ((object.ReferenceEquals(this.parmRecommendationField, value) != true)) {
                    this.parmRecommendationField = value;
                    this.RaisePropertyChanged("parmRecommendation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmRemedy {
            get {
                return this.parmRemedyField;
            }
            set {
                if ((object.ReferenceEquals(this.parmRemedyField, value) != true)) {
                    this.parmRemedyField = value;
                    this.RaisePropertyChanged("parmRemedy");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MzkValidateUserContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class MzkValidateUserContract : Pithline.FMS.TechnicalInspection.UILogic.TIService.XppObjectBase {
        
        private string parmAddressField;
        
        private string parmCompanyField;
        
        private string parmCompanyNameField;
        
        private Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkLoginType parmLoginTypeField;
        
        private string parmUserIDField;
        
        private string parmUserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmAddress {
            get {
                return this.parmAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.parmAddressField, value) != true)) {
                    this.parmAddressField = value;
                    this.RaisePropertyChanged("parmAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmCompany {
            get {
                return this.parmCompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.parmCompanyField, value) != true)) {
                    this.parmCompanyField = value;
                    this.RaisePropertyChanged("parmCompany");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmCompanyName {
            get {
                return this.parmCompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.parmCompanyNameField, value) != true)) {
                    this.parmCompanyNameField = value;
                    this.RaisePropertyChanged("parmCompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkLoginType parmLoginType {
            get {
                return this.parmLoginTypeField;
            }
            set {
                if ((this.parmLoginTypeField.Equals(value) != true)) {
                    this.parmLoginTypeField = value;
                    this.RaisePropertyChanged("parmLoginType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmUserID {
            get {
                return this.parmUserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.parmUserIDField, value) != true)) {
                    this.parmUserIDField = value;
                    this.RaisePropertyChanged("parmUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmUserName {
            get {
                return this.parmUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.parmUserNameField, value) != true)) {
                    this.parmUserNameField = value;
                    this.RaisePropertyChanged("parmUserName");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EEPActionStep", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum EEPActionStep : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProcessNone = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProcessCBL = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProcessLicenseReg = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GenQuery = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServiceSchedulling = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProcessEPStep1 = 97,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProcessEPStep2 = 98,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProcessEPStep3 = 99,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JobCardDetails = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WorkComplete = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MaintenceServiceSheduling = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SelectSupplier = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConfirmDriver = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CTermQuoteStep1 = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CTermQuoteStep2 = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CTermQuoteStep3 = 102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Procurment = 105,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Procurment_AccRej = 106,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AwaitInspectionDetail = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AwaitInspectionConfirmation = 107,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AwaitInspectionDataCapture = 108,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AwaitInspectionAcceptance = 109,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AwaitDamageConfirmation = 110,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AwaitServiceBookingDetail = 111,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AwaitSupplierSelection = 112,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AwaitServiceBookingConfirmation = 113,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completed = 114,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AwaitCollectionDetail = 115,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AwaitVendorSelection = 116,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AwaitCollectionConfirmation = 117,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AwaitCollectionDataCapture = 118,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProvideCollectionDetails = 119,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SelectThirdPartyCollection = 120,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConfirmVehicleCollection = 121,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CaptureInspectionData = 122,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CustomerApprovals = 123,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UploadDrives = 124,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CreateDrivers = 125,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Live = 126,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UploadDevices = 127,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CreateDevices = 128,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ManageContract_Customer = 129,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ManageContract_Contract = 130,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ManageContract_AccRej = 131,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CaptureFuelCardDetails = 132,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConfirmDeliveryAddress = 133,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReceiveFuelCard = 134,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AwaitDriverCollection = 135,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AwaitDeliveryConfirmation = 136,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AwaitCourierCollection = 137,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AwaitInvoice = 138,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CaptureETagReplacementReason = 139,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReceiveETag = 140,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AwaitDeliverytoHyper = 141,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProvideVehicleInspectionDetails = 142,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AwaitTechnicalInspection = 143,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MzkLoginType", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum MzkLoginType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Driver = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Courier = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Customer = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/netfx/2009/05/routing", ConfigurationName="TIService.IRequestReplyRouter")]
    public interface IRequestReplyRouter {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRequestReplyRouterChannel : Pithline.FMS.TechnicalInspection.UILogic.TIService.IRequestReplyRouter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RequestReplyRouterClient : System.ServiceModel.ClientBase<Pithline.FMS.TechnicalInspection.UILogic.TIService.IRequestReplyRouter>, Pithline.FMS.TechnicalInspection.UILogic.TIService.IRequestReplyRouter {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RequestReplyRouterClient() : 
                base(RequestReplyRouterClient.GetDefaultBinding(), RequestReplyRouterClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.reqReplyEndpoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RequestReplyRouterClient(EndpointConfiguration endpointConfiguration) : 
                base(RequestReplyRouterClient.GetBindingForEndpoint(endpointConfiguration), RequestReplyRouterClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RequestReplyRouterClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RequestReplyRouterClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RequestReplyRouterClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RequestReplyRouterClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RequestReplyRouterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.reqReplyEndpoint)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportCredentialOnly;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Windows;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.reqReplyEndpoint)) {
                return new System.ServiceModel.EndpointAddress("http://srfmlbispstg01.lfmd.co.za/MicrosoftDynamicsAXAif60/TechnicalInspection/xpp" +
                        "service.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return RequestReplyRouterClient.GetBindingForEndpoint(EndpointConfiguration.reqReplyEndpoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return RequestReplyRouterClient.GetEndpointAddress(EndpointConfiguration.reqReplyEndpoint);
        }
        
        public enum EndpointConfiguration {
            
            reqReplyEndpoint,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="TIService.MzkTechnicalInspection")]
    public interface MzkTechnicalInspection {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MzkTechnicalInspection/validateUser", ReplyAction="http://tempuri.org/MzkTechnicalInspection/validateUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Pithline.FMS.TechnicalInspection.UILogic.TIService.AifFault), Action="http://tempuri.org/MzkTechnicalInspection/validateUserAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionValidateUserResponse> validateUserAsync(Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionValidateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MzkTechnicalInspection/updateStatusList", ReplyAction="http://tempuri.org/MzkTechnicalInspection/updateStatusListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Pithline.FMS.TechnicalInspection.UILogic.TIService.AifFault), Action="http://tempuri.org/MzkTechnicalInspection/updateStatusListAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionUpdateStatusListResponse> updateStatusListAsync(Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionUpdateStatusListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MzkTechnicalInspection/getTasks", ReplyAction="http://tempuri.org/MzkTechnicalInspection/getTasksResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Pithline.FMS.TechnicalInspection.UILogic.TIService.AifFault), Action="http://tempuri.org/MzkTechnicalInspection/getTasksAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionGetTasksResponse> getTasksAsync(Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionGetTasksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MzkTechnicalInspection/getUserDetails", ReplyAction="http://tempuri.org/MzkTechnicalInspection/getUserDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Pithline.FMS.TechnicalInspection.UILogic.TIService.AifFault), Action="http://tempuri.org/MzkTechnicalInspection/getUserDetailsAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionGetUserDetailsResponse> getUserDetailsAsync(Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionGetUserDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MzkTechnicalInspection/saveImage", ReplyAction="http://tempuri.org/MzkTechnicalInspection/saveImageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Pithline.FMS.TechnicalInspection.UILogic.TIService.AifFault), Action="http://tempuri.org/MzkTechnicalInspection/saveImageAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionSaveImageResponse> saveImageAsync(Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionSaveImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MzkTechnicalInspection/insertTechnicalInspection", ReplyAction="http://tempuri.org/MzkTechnicalInspection/insertTechnicalInspectionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Pithline.FMS.TechnicalInspection.UILogic.TIService.AifFault), Action="http://tempuri.org/MzkTechnicalInspection/insertTechnicalInspectionAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionInsertTechnicalInspectionResponse> insertTechnicalInspectionAsync(Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionInsertTechnicalInspectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MzkTechnicalInspection/getSubComponents", ReplyAction="http://tempuri.org/MzkTechnicalInspection/getSubComponentsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Pithline.FMS.TechnicalInspection.UILogic.TIService.AifFault), Action="http://tempuri.org/MzkTechnicalInspection/getSubComponentsAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionGetSubComponentsResponse> getSubComponentsAsync(Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionGetSubComponentsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MzkTechnicalInspectionValidateUserRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MzkTechnicalInspectionValidateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _userID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _password;
        
        public MzkTechnicalInspectionValidateUserRequest() {
        }
        
        public MzkTechnicalInspectionValidateUserRequest(string _userID, string _password) {
            this._userID = _userID;
            this._password = _password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MzkTechnicalInspectionValidateUserResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MzkTechnicalInspectionValidateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public bool response;
        
        public MzkTechnicalInspectionValidateUserResponse() {
        }
        
        public MzkTechnicalInspectionValidateUserResponse(bool response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MzkTechnicalInspectionUpdateStatusListRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MzkTechnicalInspectionUpdateStatusListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalTasksContract> _lstTasks;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _company;
        
        public MzkTechnicalInspectionUpdateStatusListRequest() {
        }
        
        public MzkTechnicalInspectionUpdateStatusListRequest(System.Collections.ObjectModel.ObservableCollection<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalTasksContract> _lstTasks, string _company) {
            this._lstTasks = _lstTasks;
            this._company = _company;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MzkTechnicalInspectionUpdateStatusListResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MzkTechnicalInspectionUpdateStatusListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalTasksContract> response;
        
        public MzkTechnicalInspectionUpdateStatusListResponse() {
        }
        
        public MzkTechnicalInspectionUpdateStatusListResponse(System.Collections.ObjectModel.ObservableCollection<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalTasksContract> response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MzkTechnicalInspectionGetTasksRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MzkTechnicalInspectionGetTasksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _company;
        
        public MzkTechnicalInspectionGetTasksRequest() {
        }
        
        public MzkTechnicalInspectionGetTasksRequest(string _userId, string _company) {
            this._userId = _userId;
            this._company = _company;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MzkTechnicalInspectionGetTasksResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MzkTechnicalInspectionGetTasksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalTasksContract> response;
        
        public MzkTechnicalInspectionGetTasksResponse() {
        }
        
        public MzkTechnicalInspectionGetTasksResponse(System.Collections.ObjectModel.ObservableCollection<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalTasksContract> response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MzkTechnicalInspectionGetUserDetailsRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MzkTechnicalInspectionGetUserDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _userID;
        
        public MzkTechnicalInspectionGetUserDetailsRequest() {
        }
        
        public MzkTechnicalInspectionGetUserDetailsRequest(string _userID) {
            this._userID = _userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MzkTechnicalInspectionGetUserDetailsResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MzkTechnicalInspectionGetUserDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkValidateUserContract response;
        
        public MzkTechnicalInspectionGetUserDetailsResponse() {
        }
        
        public MzkTechnicalInspectionGetUserDetailsResponse(Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkValidateUserContract response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MzkTechnicalInspectionSaveImageRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MzkTechnicalInspectionSaveImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<Pithline.FMS.TechnicalInspection.UILogic.TIService.Mzk_ImageContract> _imageInfo;
        
        public MzkTechnicalInspectionSaveImageRequest() {
        }
        
        public MzkTechnicalInspectionSaveImageRequest(System.Collections.ObjectModel.ObservableCollection<Pithline.FMS.TechnicalInspection.UILogic.TIService.Mzk_ImageContract> _imageInfo) {
            this._imageInfo = _imageInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MzkTechnicalInspectionSaveImageResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MzkTechnicalInspectionSaveImageResponse {
        
        public MzkTechnicalInspectionSaveImageResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MzkTechnicalInspectionInsertTechnicalInspectionRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MzkTechnicalInspectionInsertTechnicalInspectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkCaseServiceAuthorizationContract> _caseServiceAuthorization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _company;
        
        public MzkTechnicalInspectionInsertTechnicalInspectionRequest() {
        }
        
        public MzkTechnicalInspectionInsertTechnicalInspectionRequest(System.Collections.ObjectModel.ObservableCollection<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkCaseServiceAuthorizationContract> _caseServiceAuthorization, string _company) {
            this._caseServiceAuthorization = _caseServiceAuthorization;
            this._company = _company;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MzkTechnicalInspectionInsertTechnicalInspectionResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MzkTechnicalInspectionInsertTechnicalInspectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkCaseServiceAuthorizationContract> response;
        
        public MzkTechnicalInspectionInsertTechnicalInspectionResponse() {
        }
        
        public MzkTechnicalInspectionInsertTechnicalInspectionResponse(System.Collections.ObjectModel.ObservableCollection<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkCaseServiceAuthorizationContract> response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MzkTechnicalInspectionGetSubComponentsRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MzkTechnicalInspectionGetSubComponentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<long> _lstCaseService;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _company;
        
        public MzkTechnicalInspectionGetSubComponentsRequest() {
        }
        
        public MzkTechnicalInspectionGetSubComponentsRequest(System.Collections.ObjectModel.ObservableCollection<long> _lstCaseService, string _company) {
            this._lstCaseService = _lstCaseService;
            this._company = _company;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MzkTechnicalInspectionGetSubComponentsResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class MzkTechnicalInspectionGetSubComponentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkCaseCategoryAuthorizationContract> response;
        
        public MzkTechnicalInspectionGetSubComponentsResponse() {
        }
        
        public MzkTechnicalInspectionGetSubComponentsResponse(System.Collections.ObjectModel.ObservableCollection<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkCaseCategoryAuthorizationContract> response) {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MzkTechnicalInspectionChannel : Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspection, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MzkTechnicalInspectionClient : System.ServiceModel.ClientBase<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspection>, Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspection {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MzkTechnicalInspectionClient() : 
                base(MzkTechnicalInspectionClient.GetDefaultBinding(), MzkTechnicalInspectionClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_MzkTechnicalInspection.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MzkTechnicalInspectionClient(EndpointConfiguration endpointConfiguration) : 
                base(MzkTechnicalInspectionClient.GetBindingForEndpoint(endpointConfiguration), MzkTechnicalInspectionClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MzkTechnicalInspectionClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MzkTechnicalInspectionClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MzkTechnicalInspectionClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MzkTechnicalInspectionClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MzkTechnicalInspectionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionValidateUserResponse> Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspection.validateUserAsync(Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionValidateUserRequest request) {
            return base.Channel.validateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionValidateUserResponse> validateUserAsync(string _userID, string _password) {
            Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionValidateUserRequest inValue = new Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionValidateUserRequest();
            inValue._userID = _userID;
            inValue._password = _password;
            return ((Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspection)(this)).validateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionUpdateStatusListResponse> Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspection.updateStatusListAsync(Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionUpdateStatusListRequest request) {
            return base.Channel.updateStatusListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionUpdateStatusListResponse> updateStatusListAsync(System.Collections.ObjectModel.ObservableCollection<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalTasksContract> _lstTasks, string _company) {
            Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionUpdateStatusListRequest inValue = new Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionUpdateStatusListRequest();
            inValue._lstTasks = _lstTasks;
            inValue._company = _company;
            return ((Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspection)(this)).updateStatusListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionGetTasksResponse> Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspection.getTasksAsync(Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionGetTasksRequest request) {
            return base.Channel.getTasksAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionGetTasksResponse> getTasksAsync(string _userId, string _company) {
            Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionGetTasksRequest inValue = new Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionGetTasksRequest();
            inValue._userId = _userId;
            inValue._company = _company;
            return ((Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspection)(this)).getTasksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionGetUserDetailsResponse> Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspection.getUserDetailsAsync(Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionGetUserDetailsRequest request) {
            return base.Channel.getUserDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionGetUserDetailsResponse> getUserDetailsAsync(string _userID) {
            Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionGetUserDetailsRequest inValue = new Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionGetUserDetailsRequest();
            inValue._userID = _userID;
            return ((Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspection)(this)).getUserDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionSaveImageResponse> Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspection.saveImageAsync(Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionSaveImageRequest request) {
            return base.Channel.saveImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionSaveImageResponse> saveImageAsync(System.Collections.ObjectModel.ObservableCollection<Pithline.FMS.TechnicalInspection.UILogic.TIService.Mzk_ImageContract> _imageInfo) {
            Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionSaveImageRequest inValue = new Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionSaveImageRequest();
            inValue._imageInfo = _imageInfo;
            return ((Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspection)(this)).saveImageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionInsertTechnicalInspectionResponse> Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspection.insertTechnicalInspectionAsync(Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionInsertTechnicalInspectionRequest request) {
            return base.Channel.insertTechnicalInspectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionInsertTechnicalInspectionResponse> insertTechnicalInspectionAsync(System.Collections.ObjectModel.ObservableCollection<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkCaseServiceAuthorizationContract> _caseServiceAuthorization, string _company) {
            Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionInsertTechnicalInspectionRequest inValue = new Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionInsertTechnicalInspectionRequest();
            inValue._caseServiceAuthorization = _caseServiceAuthorization;
            inValue._company = _company;
            return ((Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspection)(this)).insertTechnicalInspectionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionGetSubComponentsResponse> Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspection.getSubComponentsAsync(Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionGetSubComponentsRequest request) {
            return base.Channel.getSubComponentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionGetSubComponentsResponse> getSubComponentsAsync(System.Collections.ObjectModel.ObservableCollection<long> _lstCaseService, string _company) {
            Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionGetSubComponentsRequest inValue = new Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspectionGetSubComponentsRequest();
            inValue._lstCaseService = _lstCaseService;
            inValue._company = _company;
            return ((Pithline.FMS.TechnicalInspection.UILogic.TIService.MzkTechnicalInspection)(this)).getSubComponentsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_MzkTechnicalInspection)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportCredentialOnly;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Windows;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_MzkTechnicalInspection)) {
                return new System.ServiceModel.EndpointAddress("http://srfmlbispstg01.lfmd.co.za/MicrosoftDynamicsAXAif60/TechnicalInspection/xpp" +
                        "service.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return MzkTechnicalInspectionClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_MzkTechnicalInspection);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return MzkTechnicalInspectionClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_MzkTechnicalInspection);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_MzkTechnicalInspection,
        }
    }
}
